// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE-HL_BBp8hoxVYQvFfZ0mIBkMikAvdXk',
    appId: '1:418682335554:web:6d0f69d4bd8f1eb85c58db',
    messagingSenderId: '418682335554',
    projectId: 'finance-app-a505b',
    authDomain: 'finance-app-a505b.firebaseapp.com',
    storageBucket: 'finance-app-a505b.firebasestorage.app',
    measurementId: 'G-3VDVZ07Q5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqeMn-HmnO0NBI7p35JaoWtiGCoUYl5FA',
    appId: '1:418682335554:android:bd8cb53ded9d100a5c58db',
    messagingSenderId: '418682335554',
    projectId: 'finance-app-a505b',
    storageBucket: 'finance-app-a505b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxRE7J7XaEpVPL8FulCnzBv72YSSS5FFw',
    appId: '1:418682335554:ios:a974029b9fbb22ca5c58db',
    messagingSenderId: '418682335554',
    projectId: 'finance-app-a505b',
    storageBucket: 'finance-app-a505b.firebasestorage.app',
    iosBundleId: 'com.example.financeManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxRE7J7XaEpVPL8FulCnzBv72YSSS5FFw',
    appId: '1:418682335554:ios:a974029b9fbb22ca5c58db',
    messagingSenderId: '418682335554',
    projectId: 'finance-app-a505b',
    storageBucket: 'finance-app-a505b.firebasestorage.app',
    iosBundleId: 'com.example.financeManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE-HL_BBp8hoxVYQvFfZ0mIBkMikAvdXk',
    appId: '1:418682335554:web:6171aa48eb4715e35c58db',
    messagingSenderId: '418682335554',
    projectId: 'finance-app-a505b',
    authDomain: 'finance-app-a505b.firebaseapp.com',
    storageBucket: 'finance-app-a505b.firebasestorage.app',
    measurementId: 'G-25Z2JXJ9SX',
  );
}
